# Numpy 
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

In [1]:
# Import
import numpy as np

# Creating
There are lots of ways to create the arrays.

In [2]:
# From list to array
list1 = [1, 2, 3]
np.array(list1)

array([1, 2, 3])

In [3]:
# From list to 2darray
matrix1 = [[1,2,3],[4,5,6],[7,8,9]]
np.array(matrix1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# Arange
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# Arange with space
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [6]:
# Zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
# Zeros 2darray
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# Ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
# Ones 2darray
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# Linspace
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [11]:
# Eye
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# Rand
np.random.rand(10)

array([0.84947583, 0.12563145, 0.76386606, 0.11658065, 0.17705789,
       0.09129223, 0.64665453, 0.89693354, 0.67866695, 0.12189701])

In [13]:
# Rand 2darray
np.random.rand(3,3)

array([[0.58056717, 0.05174551, 0.32420945],
       [0.39496409, 0.74807003, 0.31389871],
       [0.85608072, 0.23452392, 0.21349658]])

In [14]:
# Randint
np.random.randint(0,100,10)

array([ 3, 59, 52, 77, 95, 60, 46,  8, 38, 57])

# Attributes and Methods
There are lots of useful attriburs and methods of the arrays.

In [15]:
# Value assignment
array1 = np.random.randint(0,100,20)
array1

array([92, 42, 43, 46, 13, 74, 22, 38, 23, 76, 24, 87, 58, 34, 61, 22, 66,
       87, 65, 33])

In [16]:
# Min
array1.min()

13

In [17]:
# Argmin
array1.argmin()

4

In [18]:
# Max
array1.max()

92

In [19]:
# Argmax
array1.argmax()

0

In [20]:
# Reshape
array1.reshape(4,5)

array([[92, 42, 43, 46, 13],
       [74, 22, 38, 23, 76],
       [24, 87, 58, 34, 61],
       [22, 66, 87, 65, 33]])

In [21]:
# Shape
array1.shape

(20,)

In [22]:
# Row vector
array1.reshape(1,20)

array([[92, 42, 43, 46, 13, 74, 22, 38, 23, 76, 24, 87, 58, 34, 61, 22,
        66, 87, 65, 33]])

In [23]:
# Row vector shape
array1.reshape(1,20).shape

(1, 20)

In [24]:
# Column vector
array1.reshape(20,1)

array([[92],
       [42],
       [43],
       [46],
       [13],
       [74],
       [22],
       [38],
       [23],
       [76],
       [24],
       [87],
       [58],
       [34],
       [61],
       [22],
       [66],
       [87],
       [65],
       [33]])

In [25]:
# Column vector shape
array1.reshape(20,1).shape

(20, 1)

In [26]:
# Dtype
array1.dtype

dtype('int32')

# Operations
There are lots of useful operations that can performed on the arrays.

In [27]:
# Value assignment
array2 = np.arange(0,10)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# Array addition
array2 + array2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
# Array subtraction
array2 - array2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
# Array multiplication
array2 * array2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [31]:
# Array division
array2 / array2

C:\Users\HP\AppData\Local\Temp\ipykernel_10516\1627922383.py:2: RuntimeWarning: invalid value encountered in true_divide
  array2 / array2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [32]:
# Square
array2 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [33]:
# Mood 
array2 % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [34]:
# Square roots (universal array function)
np.sqrt(array2)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [35]:
# Exponential (universal array function)
np.exp(array2)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [36]:
# Log (universal array function)
np.log(array2)

C:\Users\HP\AppData\Local\Temp\ipykernel_10516\376286691.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(array2)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [37]:
# Max (universal array function)
np.max(array2)

9

# Indexing and Selection
Indexing and slicing are possible on the arrays.

### 1D Array Indexing

In [38]:
# Value assignment
array3 = np.arange(0,10)
array3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
#Get a value at an index
array3[3]

3

In [40]:
#Get values in a range
array3[1:5]

array([1, 2, 3, 4])

In [41]:
#Setting a value with index range
array3[:5] = 100
array3

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [42]:
# Copy
array4 = array3.copy()
array4[:5] = [0, 1, 2, 3, 4]
print(array3)
print(array4)

[100 100 100 100 100   5   6   7   8   9]
[0 1 2 3 4 5 6 7 8 9]


### 2D Array Indexing

In [43]:
# Value assignment
matrix2 = np.array(([5,10,15],[20,25,30],[35,40,45]))
matrix2

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [44]:
#Indexing row 
matrix2[1,:]

array([20, 25, 30])

In [45]:
#Indexing row out of order
matrix2[[2,1,0],:]

array([[35, 40, 45],
       [20, 25, 30],
       [ 5, 10, 15]])

In [46]:
#Indexing column 
matrix2[:,1]

array([10, 25, 40])

In [47]:
#Indexing column out of order
matrix2[:,[1,2,0]]

array([[10, 15,  5],
       [25, 30, 20],
       [40, 45, 35]])

In [48]:
# Getting individual element value
matrix2[2,2]

45

In [49]:
# 2D array slicing
matrix2[0:2,0:2]

array([[ 5, 10],
       [20, 25]])

### Selection

In [50]:
# Variable assignment
array5 = np.arange(1,11)
array5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
# Selection condition
array5 > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [52]:
# Select with assignment
bool_array5 = array5>4
array5[bool_array5]

array([ 5,  6,  7,  8,  9, 10])

In [53]:
# Select directly
array5[array5>4]

array([ 5,  6,  7,  8,  9, 10])

In [54]:
# Select with value assignment
int_array5 = 4
array5[array5>int_array5]

array([ 5,  6,  7,  8,  9, 10])