# Numpy 
NumPy is the fundamental package for scientific computing in the Python programming language.

In [1]:
# Import
import numpy as np

# Creating
There are lots of ways to create the arrays.

In [2]:
# From a list to an array
list1 = [1, 2, 3]
np.array(list1)

array([1, 2, 3])

In [3]:
# From a list to a 2darray
list2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(list2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# Arange
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# Arange with a space
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [6]:
# Zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
# Zeros 2D
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# Ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
# Ones 2D
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# Linspace
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [11]:
# Eye
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# Rand
np.random.rand(10)

array([0.9033433 , 0.66886686, 0.32320895, 0.90271585, 0.15588064,
       0.85334283, 0.80756524, 0.13515773, 0.48416449, 0.77203677])

In [13]:
# Rand 2D
np.random.rand(3, 3)

array([[0.7253535 , 0.15985601, 0.02938655],
       [0.63853037, 0.92196648, 0.27801639],
       [0.15731036, 0.90284705, 0.41588503]])

In [14]:
# Randint
np.random.randint(0, 100, 10)

array([31, 29, 35, 27, 19, 16,  7,  3, 17, 61])

# Attributes and Methods
There are lots of useful attriburs and methods of the arrays.

In [15]:
# Variable assignment
array1 = np.arange(1, 10)
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# Min
array1.min()

1

In [17]:
# Argmin
array1.argmin()

0

In [18]:
# Max
array1.max()

9

In [19]:
# Argmax
array1.argmax()

8

In [20]:
# Shape
array1.shape

(9,)

In [21]:
# Row vector
array1.reshape(1, 9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [22]:
# Row vector shape
array1.reshape(1, 9).shape

(1, 9)

In [23]:
# Column vector
array1.reshape(9, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [24]:
# Column vector shape
array1.reshape(9, 1).shape

(9, 1)

In [25]:
# Dtype
array1.dtype

dtype('int32')

In [26]:
# Reshape
array2 = array1.reshape(3, -1)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
# Transpose
array2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [28]:
# Flatten
array2.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
# Copy
array3 = array1.copy()
array3[:5] = [0, 0, 0, 0, 0]
array3

array([0, 0, 0, 0, 0, 6, 7, 8, 9])

In [30]:
# Variable assignment
matrix1 = np.array([[1, 1], [0, 1]])
matrix2 = np.array([[2, 0], [3, 4]])

In [31]:
# Vstack
np.vstack((matrix1, matrix2))

array([[1, 1],
       [0, 1],
       [2, 0],
       [3, 4]])

In [32]:
# Hstack
np.hstack((matrix1, matrix2))

array([[1, 1, 2, 0],
       [0, 1, 3, 4]])

In [33]:
# np.column_stack
np.column_stack((array1, array3))

array([[1, 0],
       [2, 0],
       [3, 0],
       [4, 0],
       [5, 0],
       [6, 6],
       [7, 7],
       [8, 8],
       [9, 9]])

In [34]:
# Del
del array1
array3

array([0, 0, 0, 0, 0, 6, 7, 8, 9])

# Operations
There are lots of useful operations that can performed on the arrays.

In [35]:
# Variable assignment
array4 = np.arange(0, 10)
array4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# Array addition
array4 + array4

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
# Array subtraction
array4 - array4

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
# Array multiplication
array4 * array4

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [39]:
# Array division
array4 / array4

C:\Users\HP\AppData\Local\Temp\ipykernel_12912\1138492661.py:2: RuntimeWarning: invalid value encountered in true_divide
  array4 / array4


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [40]:
# Square
array4 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [41]:
# Mood 
array4 % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [42]:
# Condition
array4 < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [43]:
# Max
array4.max()

9

In [44]:
# Sum
array4.sum()

45

In [45]:
# Square roots (universal array function)
np.sqrt(array4)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [46]:
# Exponential (universal array function)
np.exp(array4)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [47]:
# Log (universal array function)
np.log(array4)

C:\Users\HP\AppData\Local\Temp\ipykernel_12912\3863638674.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(array4)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [48]:
# Max (universal array function)
np.max(array4)

9

In [49]:
# Sum (universal array function)
np.sum(array4)

45

In [50]:
# Variable assignment
matrix3 = np.array([[1, 1], [0, 1]])
matrix4 = np.array([[2, 0], [3, 4]])

In [51]:
# Elementwise product
matrix3 * matrix4

array([[2, 0],
       [0, 4]])

In [52]:
# Matrix product
matrix3 @ matrix4
#array3.dot(array4)

array([[5, 4],
       [3, 4]])

# Indexing, Slicing, Iteration and Selection
Indexing, slicing, iteration and selection are possible on the arrays.

### 1D Array

In [53]:
# Variable assignment
array5 = np.arange(0, 10)
array5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
# Get a value at an index
array5[3]

3

In [55]:
# Get a value at the last index
array5[-1]

9

In [56]:
# Get values in a range
array5[1:5]

array([1, 2, 3, 4])

In [57]:
# Get values backwards
array5[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [58]:
# Get value but go in step sizes of 2
array5[::2]

array([0, 2, 4, 6, 8])

In [59]:
# Setting a value with index
array5[0] = 10
array5

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [60]:
# Setting a value with index range
array5[1:5] = 10
array5

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9])

In [61]:
# Setting a value with a list of indices
array5[[0, 2, 4]] = 100
array5

array([100,  10, 100,  10, 100,   5,   6,   7,   8,   9])

### 2D Array

In [62]:
# Variable assignment
matrix5 = np.array(([5, 10, 15], [20, 25, 30], [35, 40, 45]))
matrix5

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [63]:
# Indexing a row 
matrix5[1, :]

array([20, 25, 30])

In [64]:
# Indexing the last row
matrix5[-1, :]

array([35, 40, 45])

In [65]:
# Indexing rows out of order
matrix5[[2, 1, 0], :]

array([[35, 40, 45],
       [20, 25, 30],
       [ 5, 10, 15]])

In [66]:
# Indexing a column 
matrix5[:, 1]

array([10, 25, 40])

In [67]:
# Indexing the last column
matrix5[:, -1]

array([15, 30, 45])

In [68]:
# Indexing columns out of order
matrix5[:, [1, 2, 0]]

array([[10, 15,  5],
       [25, 30, 20],
       [40, 45, 35]])

In [69]:
# Getting an individual element value
matrix5[2, 2]

45

In [70]:
# 2D array slicing
matrix5[0:2, 0:2]

array([[ 5, 10],
       [20, 25]])

In [71]:
# 2D array column eslicing
matrix5[:, 0:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

### Iteration

In [72]:
# Variable assignment
matrix6 = np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9]))
matrix6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
#Iterating over multidimensional arrays
for row in matrix6:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [74]:
#Iterating over multidimensional arrays on each element
for element in matrix6.flatten():
    print(element)

1
2
3
4
5
6
7
8
9


### Selection

In [75]:
# Variable assignment
array6 = np.arange(1, 11)
array6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
# Select condition
array6 > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [77]:
# Select directly
array6[array6 > 4]

array([ 5,  6,  7,  8,  9, 10])

In [78]:
# Select with an assignment
bool_array6 = array6 > 4
array6[bool_array6]

array([ 5,  6,  7,  8,  9, 10])

In [79]:
# Select with a value assignment
int_array6 = 4
array5[array6 > int_array6]

array([100,   5,   6,   7,   8,   9])

In [80]:
# Change directly
array6[array6 > 4] = 0
array6

array([1, 2, 3, 4, 0, 0, 0, 0, 0, 0])

In [81]:
# Variable assignment
matrix7 = np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9]))
matrix7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
# Select condition 2D
matrix7 > 4

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [83]:
# Select directly 2D
matrix7[matrix7 > 4]

array([5, 6, 7, 8, 9])

In [84]:
# Change directly 2D
matrix7[matrix7 > 4] = 0
matrix7

array([[1, 2, 3],
       [4, 0, 0],
       [0, 0, 0]])